version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  build:
    commands:
      - cd deployment
      - ./build-s3-dist.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${VERSION}
  post_build:
    commands:
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml buildspec.yml || true
artifacts:
  files:
    - .git/**/*
    - deployment/**/*
    - buildspec.yml
    - CHANGELOG.md
    - docs/**/*
    - .cfnnag_*
